# Generated by Django 4.1.7 on 2023-03-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwapiDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='static/')),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
